import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const inter = localFont({
  src: [
    { path: "./fonts/inter/Inter-Thin-Beta.otf", weight: "100", style: "normal" },
    { path: "./fonts/inter/Inter-ExtraLight-BETA.otf", weight: "200", style: "normal" },
    { path: "./fonts/inter/Inter-Regular.otf", weight: "400", style: "normal" },
    { path: "./fonts/inter/Inter-Semibold.otf", weight: "600", style: "normal" },
    { path: "./fonts/inter/Inter-Bold.otf", weight: "700", style: "normal" },
    { path: "./fonts/inter/Inter-Black.otf", weight: "900", style: "normal" },
  ],
  variable: "--font-inter",
  display: "swap", // Uncomment for better performance.
});


const poppins = localFont({
  src: [
    { path: "./fonts/poppins/Poppins-Thin.ttf", weight: "100", style: "normal" },
    { path: "./fonts/poppins/Poppins-ExtraLight.ttf", weight: "200", style: "normal" },
    { path: "./fonts/poppins/Poppins-Regular.ttf", weight: "400", style: "normal" },
    { path: "./fonts/poppins/Poppins-Semibold.ttf", weight: "600", style: "normal" },
    { path: "./fonts/poppins/Poppins-Bold.ttf", weight: "700", style: "normal" },
    { path: "./fonts/poppins/Poppins-Black.ttf", weight: "900", style: "normal" },
  ],
  variable: "--font-poppins",
  display: "swap", // Uncomment for better performance.
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${poppins.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
